### ISSUE TITLE
Example how to use the layer

### ISSUE THREAD

**Issue by ivicadimitrovski** [lucamasera/AWX#2]
I'm getting an error (TypeError: 'module' object is not callable) when try to use the AWX layer. Can you please provide an example code of how to use the layer in simple ANN setup.

**Comment by rafaelbrpg** [comment]
Hello! Thanks for shared your code! I would like a demo, showing how i can use AWX class. In this moment, i receive this error:

AttributeError: 'NoneType' object has no attribute '_keras_shape'

Thanks!

**Comment by lucamasera** [comment]
I hope that the example code clarified how the code works! Unfortunately I was not able to reproduce you error.
